# permissions for end users to edit crons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cron-editor-role
rules:
- apiGroups:
  - jobber.ishankhare.dev
  resources:
  - crons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jobber.ishankhare.dev
  resources:
  - crons/status
  verbs:
  - get
